export const CATALOG_BACKPACKS = {
  type: "tourism",
  item: [
    {
      id: 1,
      name: "Xiaomi Mi Classic Business Backpack",
      imgSrc: "Catalog_Images/Backpacks/895700.jpg",
      price: 2130,
      firm: "Xiaomi",
    },
    {
      id: 2,
      name: "XD Design Bobby Compact",
      imgSrc: "Catalog_Images/Backpacks/1274013.jpg",
      price: 6990,
      firm: "XD Design",
    },
    {
      id: 3,
      name: "Xiaomi Mi Colorful Small Backpack",
      imgSrc: "Catalog_Images/Backpacks/1499702.jpg",
      price: 590,
      firm: "Xiaomi",
    },
    {
      id: 4,
      name: "Xiaomi City Backpack",
      imgSrc: "Catalog_Images/Backpacks/1572364.jpg",
      price: 2999,
      firm: "Xiaomi",
    },
    {
      id: 5,
      name: "XD Design Bobby",
      imgSrc: "Catalog_Images/Backpacks/1274014.jpg",
      price: 6990,
      firm: "XD Design",
    },
    {
      id: 6,
      name: "Lenovo B210 Casual Backpack",
      imgSrc: "Catalog_Images/Backpacks/1323608.jpg",
      price: 1490,
      firm: "Lenovo",
    },
    {
      id: 7,
      name: "HP Omen Gaming Backpack",
      imgSrc: "Catalog_Images/Backpacks/1272176.jpg",
      price: 4060,
      firm: "HP",
    },
    {
      id: 8,
      name: "HP Odyssey Backpack",
      imgSrc: "Catalog_Images/Backpacks/1272169.jpg",
      price: 3360,
      firm: "HP",
    },
    {
      id: 9,
      name: "Dell Pro Backpack",
      imgSrc: "Catalog_Images/Backpacks/1756146.jpg",
      price: 3300,
      firm: "Dell",
    },
    {
      id: 10,
      name: "Dell Gaming Lite Backpack",
      imgSrc: "Catalog_Images/Backpacks/1954844.jpg",
      price: 2090,
      firm: "Dell",
    },
  ],
};
