import { baseUrl } from "./BASE_URL"

export const CATALOG_SOCCERBALLS = {
  goodsItem: [
    {
      id: 1,
      name: "Nike RPL NK STRK - FA20",
      imgSrc: `${baseUrl}catalogImages/soccerballs/34654640299.jpg`,
      price: 2299,
      firm: "Nike",
    },
    {
      id: 2,
      name: "adidas Uniforia Training",
      imgSrc: `${baseUrl}catalogImages/soccerballs/27195620299.jpg`,
      price: 2399,
      firm: "adidas",
    },
    {
      id: 3,
      name: "Nike Flight",
      imgSrc: `${baseUrl}catalogImages/soccerballs/37304920299.jpg`,
      price: 1099,
      firm: "Nike",
    },
    {
      id: 4,
      name: "adidas FIN 20 LGE",
      imgSrc: `${baseUrl}catalogImages/soccerballs/37291600299.jpg`,
      price: 3999,
      firm: "adidas",
    },
    {
      id: 5,
      name: "adidas Uniforia League",
      imgSrc: `${baseUrl}catalogImages/soccerballs/27195570299.jpg`,
      price: 3999,
      firm: "adidas",
    },
    {
      id: 6,
      name: "Puma LALIGA 1 ACELERAR (FIFA QUALITY)",
      imgSrc: `${baseUrl}catalogImages/soccerballs/35031720299.jpg`,
      price: 2999,
      firm: "Puma",
    },
    {
      id: 7,
      name: "Nike Magia",
      imgSrc: `${baseUrl}catalogImages/soccerballs/23774500299.jpg`,
      price: 4999,
      firm: "Nike",
    },
    {
      id: 8,
      name: "Nike NK STRK TEAM 290G - SP20",
      imgSrc: `${baseUrl}catalogImages/soccerballs/30483130299.jpg`,
      price: 2199,
      firm: "Nike",
    },
    {
      id: 9,
      name: "adidas UCL Finale 20 Club",
      imgSrc: `${baseUrl}catalogImages/soccerballs/37288460299.jpg`,
      price: 1999,
      firm: "adidas",
    },
    {
      id: 10,
      name: "Select MATCH",
      imgSrc: `${baseUrl}catalogImages/soccerballs/21004490299.jpg`,
      price: 3999,
      firm: "Select",
    },
    {
      id: 11,
      name: "Nike PSG Prestige",
      imgSrc: `${baseUrl}catalogImages/soccerballs/23774430299.jpg`,
      price: 2199,
      firm: "Nike",
    },
    {
      id: 12,
      name: "Select Street Soccer",
      imgSrc: `${baseUrl}catalogImages/soccerballs/25385110299.jpg`,
      price: 2499,
      firm: "Select",
    },
    {
      id: 13,
      name: "Puma TEAMFINAL 21.2 FIFA QUALITY PRO",
      imgSrc: `${baseUrl}catalogImages/soccerballs/28401620299.jpg`,
      price: 4499,
      firm: "Puma",
    },
    {
      id: 14,
      name: "Nike Merlin",
      imgSrc: `${baseUrl}catalogImages/soccerballs/24540890299.jpg`,
      price: 1099,
      firm: "Nike",
    },
  ],
};
